/**
 * PartThumbnail — small SVG illustrations for each part kind.
 *
 * Used in the palette cards to give a visual preview.
 * These are presentation-only: no event handlers, no interactivity.
 */

import React from 'react';
import { getSidecar } from '../model/parts-registry.js';

const S = 48; // internal coordinate space

// SVG art URLs — generated by Vite from vendored bw-parts SVGs.
// In Node tests, this is undefined (no bundler); the switch fallback handles it.
let svgUrls = null;
try {
  if (typeof import.meta.glob === 'function') {
    svgUrls = import.meta.glob('../parts-data/*.svg', { eager: true, query: '?url', import: 'default' });
  }
} catch { /* Node: no glob */ }

function getSvgUrl(kind) {
  if (!svgUrls) return null;
  const key = `../parts-data/${kind}.svg`;
  return svgUrls[key] || null;
}

export function PartThumbnail({ kind, color, params, displaySize }) {
  const w = displaySize || S;
  const h = displaySize || S;
  const cx = S / 2, cy = S / 2;

  // Prefer bw-parts SVG art when available
  const svgUrl = getSvgUrl(kind);
  if (svgUrl) {
    return (
      <img src={svgUrl} width={w} height={h} alt={kind}
        style={{ objectFit: 'contain' }} />
    );
  }

  // Fallback to hand-drawn inline SVG
  switch (kind) {
    case 'vcc':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <line x1={cx} y1={cy + 12} x2={cx} y2={cy} stroke="#e74c3c" strokeWidth={2} />
          <line x1={cx - 10} y1={cy} x2={cx + 10} y2={cy} stroke="#e74c3c" strokeWidth={2} />
          <text x={cx} y={cy - 4} textAnchor="middle" fill="#e74c3c" fontSize={8} fontFamily="monospace" fontWeight="bold">VCC</text>
        </svg>
      );
    case 'gnd':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <line x1={cx} y1={cy - 8} x2={cx} y2={cy} stroke="#3498db" strokeWidth={2} />
          <line x1={cx - 10} y1={cy} x2={cx + 10} y2={cy} stroke="#3498db" strokeWidth={2} />
          <line x1={cx - 7} y1={cy + 4} x2={cx + 7} y2={cy + 4} stroke="#3498db" strokeWidth={2} />
          <line x1={cx - 4} y1={cy + 8} x2={cx + 4} y2={cy + 8} stroke="#3498db" strokeWidth={2} />
        </svg>
      );
    case 'resistor':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <line x1={4} y1={cy} x2={12} y2={cy} stroke="#999" strokeWidth={1.5} />
          <rect x={12} y={cy - 5} width={24} height={10} rx={2} fill="#e0c890" stroke="#b8a060" strokeWidth={1} />
          {/* Color bands */}
          <rect x={16} y={cy - 5} width={2} height={10} fill="#8B4513" />
          <rect x={20} y={cy - 5} width={2} height={10} fill="#111" />
          <rect x={24} y={cy - 5} width={2} height={10} fill="#e74c3c" />
          <rect x={30} y={cy - 5} width={2} height={10} fill="#C0A000" />
          <line x1={36} y1={cy} x2={44} y2={cy} stroke="#999" strokeWidth={1.5} />
        </svg>
      );
    case 'led': {
      const ledColor = params?.color || color || 'red';
      const fill = ledColor === 'white' ? '#eee' : ledColor;
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <line x1={4} y1={cy} x2={14} y2={cy} stroke="#999" strokeWidth={1.5} />
          {/* LED body — triangle + flat */}
          <polygon points={`${14},${cy - 8} ${14},${cy + 8} ${30},${cy}`} fill={fill} opacity={0.8} stroke={fill} strokeWidth={1} />
          <line x1={30} y1={cy - 8} x2={30} y2={cy + 8} stroke={fill} strokeWidth={1.5} />
          {/* Light rays */}
          <line x1={32} y1={cy - 6} x2={36} y2={cy - 10} stroke={fill} strokeWidth={0.8} opacity={0.6} />
          <line x1={33} y1={cy - 2} x2={38} y2={cy - 4} stroke={fill} strokeWidth={0.8} opacity={0.6} />
          <line x1={30} y1={cy} x2={44} y2={cy} stroke="#999" strokeWidth={1.5} />
        </svg>
      );
    }
    case 'capacitor':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <line x1={4} y1={cy} x2={20} y2={cy} stroke="#999" strokeWidth={1.5} />
          <line x1={20} y1={cy - 8} x2={20} y2={cy + 8} stroke="#34495e" strokeWidth={2.5} />
          <path d={`M 26 ${cy - 8} Q 24 ${cy} 26 ${cy + 8}`} fill="none" stroke="#34495e" strokeWidth={2.5} />
          <line x1={28} y1={cy} x2={44} y2={cy} stroke="#999" strokeWidth={1.5} />
        </svg>
      );
    case 'potentiometer':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={10} y={cy - 8} width={28} height={16} rx={3} fill="#2c3e50" stroke="#9b59b6" strokeWidth={1} />
          {/* Shaft */}
          <circle cx={cx} cy={cy} r={5} fill="#555" stroke="#9b59b6" strokeWidth={1} />
          <line x1={cx} y1={cy} x2={cx + 4} y2={cy - 3} stroke="#bbb" strokeWidth={1.5} />
          {/* Terminals */}
          <line x1={4} y1={cy + 6} x2={10} y2={cy + 6} stroke="#999" strokeWidth={1} />
          <line x1={cx} y1={cy - 8} x2={cx} y2={cy - 14} stroke="#999" strokeWidth={1} />
          <line x1={38} y1={cy + 6} x2={44} y2={cy + 6} stroke="#999" strokeWidth={1} />
        </svg>
      );
    case 'button':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={12} y={cy - 8} width={24} height={16} rx={3} fill="#2c3e50" stroke="#f39c12" strokeWidth={1} />
          <circle cx={cx} cy={cy} r={4} fill="#f39c12" />
          <line x1={4} y1={cy} x2={12} y2={cy} stroke="#999" strokeWidth={1.5} />
          <line x1={36} y1={cy} x2={44} y2={cy} stroke="#999" strokeWidth={1.5} />
        </svg>
      );
    case 'buzzer':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <circle cx={cx} cy={cy} r={10} fill="#1a1a2e" stroke="#1abc9c" strokeWidth={1.5} />
          <circle cx={cx} cy={cy} r={3} fill="#1abc9c" />
          <line x1={4} y1={cy} x2={14} y2={cy} stroke="#999" strokeWidth={1.5} />
          <line x1={34} y1={cy} x2={44} y2={cy} stroke="#999" strokeWidth={1.5} />
          {/* Sound waves */}
          <path d={`M 36 ${cy - 5} Q 40 ${cy} 36 ${cy + 5}`} fill="none" stroke="#1abc9c" strokeWidth={0.8} opacity={0.5} />
          <path d={`M 39 ${cy - 7} Q 44 ${cy} 39 ${cy + 7}`} fill="none" stroke="#1abc9c" strokeWidth={0.8} opacity={0.3} />
        </svg>
      );
    case 'mcu':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={8} y={6} width={32} height={36} rx={3} fill="#2c3e50" stroke="#7f8c8d" strokeWidth={1} />
          <text x={cx} y={cy} textAnchor="middle" fill="#ecf0f1" fontSize={6} fontFamily="monospace">STC12</text>
          {/* Pins */}
          {[0, 1, 2, 3].map(i => (
            <React.Fragment key={i}>
              <rect x={4} y={10 + i * 8} width={4} height={3} fill="#f39c12" />
              <rect x={40} y={10 + i * 8} width={4} height={3} fill="#f39c12" />
            </React.Fragment>
          ))}
        </svg>
      );
    case 'seven_segment':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={10} y={4} width={28} height={40} rx={3} fill="#111" stroke="#333" strokeWidth={1} />
          {/* 7-segment digit "8" */}
          <line x1={16} y1={8} x2={30} y2={8} stroke="#e74c3c" strokeWidth={2} />
          <line x1={16} y1={23} x2={30} y2={23} stroke="#e74c3c" strokeWidth={2} />
          <line x1={16} y1={38} x2={30} y2={38} stroke="#e74c3c" strokeWidth={2} />
          <line x1={14} y1={10} x2={14} y2={21} stroke="#e74c3c" strokeWidth={2} />
          <line x1={14} y1={25} x2={14} y2={36} stroke="#e74c3c" strokeWidth={2} />
          <line x1={32} y1={10} x2={32} y2={21} stroke="#e74c3c" strokeWidth={2} />
          <line x1={32} y1={25} x2={32} y2={36} stroke="#e74c3c" strokeWidth={2} />
        </svg>
      );
    case 'char_lcd':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={2} y={10} width={44} height={28} rx={3} fill="#1a4030" stroke="#2980b9" strokeWidth={1} />
          <rect x={6} y={14} width={36} height={20} rx={2} fill="#2a6040" />
          <text x={cx} y={cy + 2} textAnchor="middle" fill="#3c8" fontSize={7} fontFamily="monospace">Hello</text>
        </svg>
      );
    case 'led_matrix':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={8} y={8} width={32} height={32} rx={2} fill="#111" stroke="#27ae60" strokeWidth={1} />
          {/* 4x4 dot grid */}
          {[0, 1, 2, 3].map(r => [0, 1, 2, 3].map(c => (
            <circle key={`${r}${c}`} cx={14 + c * 8} cy={14 + r * 8} r={2}
              fill={(r + c) % 2 === 0 ? '#2ecc71' : '#1a3a20'} />
          )))}
        </svg>
      );
    case 'led_cube':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          {/* Simple 3D cube */}
          <polygon points="12,16 24,10 36,16 24,22" fill="none" stroke="#2ecc71" strokeWidth={1} />
          <polygon points="12,16 12,32 24,38 24,22" fill="none" stroke="#2ecc71" strokeWidth={1} />
          <polygon points="24,22 24,38 36,32 36,16" fill="none" stroke="#2ecc71" strokeWidth={1} />
          {/* Glow dots */}
          <circle cx={18} cy={18} r={1.5} fill="#2ecc71" opacity={0.6} />
          <circle cx={30} cy={18} r={1.5} fill="#2ecc71" opacity={0.4} />
          <circle cx={24} cy={30} r={1.5} fill="#2ecc71" opacity={0.8} />
        </svg>
      );
    case 'shift_register':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={8} y={10} width={32} height={28} rx={2} fill="#2c3e50" stroke="#8e44ad" strokeWidth={1} />
          <text x={cx} y={cy - 1} textAnchor="middle" fill="#ddd" fontSize={5} fontFamily="monospace">74HC</text>
          <text x={cx} y={cy + 6} textAnchor="middle" fill="#ddd" fontSize={5} fontFamily="monospace">595</text>
          <circle cx={12} cy={14} r={2} fill="#444" />
          {[0, 1, 2].map(i => <rect key={i} x={4} y={18 + i * 7} width={4} height={3} fill="#8e44ad" />)}
          {[0, 1, 2].map(i => <rect key={i} x={40} y={18 + i * 7} width={4} height={3} fill="#8e44ad" />)}
        </svg>
      );
    case 'ir_receiver':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <path d={`M ${cx - 8} ${cy + 8} L ${cx - 8} ${cy - 4} A 8 8 0 0 1 ${cx + 8} ${cy - 4} L ${cx + 8} ${cy + 8} Z`}
            fill="#1a1a2e" stroke="#c0392b" strokeWidth={1.5} />
          <circle cx={cx} cy={cy - 2} r={3} fill="#c0392b" opacity={0.6} />
          {[0, 1, 2].map(i => <line key={i} x1={cx - 6 + i * 6} y1={cy + 8} x2={cx - 6 + i * 6} y2={cy + 14} stroke="#999" strokeWidth={1} />)}
        </svg>
      );
    case 'temp_sensor':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <path d={`M ${cx - 5} ${cy + 8} L ${cx - 5} ${cy - 8} A 5 5 0 0 1 ${cx + 5} ${cy - 8} L ${cx + 5} ${cy + 8} Z`}
            fill="#1a1a2e" stroke="#16a085" strokeWidth={1.5} />
          <text x={cx} y={cy + 2} textAnchor="middle" fill="#16a085" fontSize={6} fontFamily="monospace">T</text>
          {[0, 1, 2].map(i => <line key={i} x1={cx - 4 + i * 4} y1={cy + 8} x2={cx - 4 + i * 4} y2={cy + 14} stroke="#999" strokeWidth={1} />)}
        </svg>
      );
    case 'eeprom':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={12} y={10} width={24} height={28} rx={2} fill="#2c3e50" stroke="#7f8c8d" strokeWidth={1} />
          <text x={cx} y={cy + 2} textAnchor="middle" fill="#bbb" fontSize={5} fontFamily="monospace">ROM</text>
          <circle cx={16} cy={14} r={1.5} fill="#444" />
          {[0, 1, 2, 3].map(i => <rect key={i} x={8} y={16 + i * 5} width={4} height={2} fill="#7f8c8d" />)}
          {[0, 1, 2, 3].map(i => <rect key={i} x={36} y={16 + i * 5} width={4} height={2} fill="#7f8c8d" />)}
        </svg>
      );
    case 'meter':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={6} y={6} width={36} height={36} rx={4} fill="#1a1a2e" stroke="#f1c40f" strokeWidth={1.5} />
          <text x={cx} y={cy - 4} textAnchor="middle" fill="#f1c40f" fontSize={12} fontFamily="monospace" fontWeight="bold">V</text>
          <text x={cx} y={cy + 8} textAnchor="middle" fill="#ecf0f1" fontSize={7} fontFamily="monospace">5.00</text>
          {/* Probes */}
          <line x1={14} y1={42} x2={14} y2={46} stroke="#e74c3c" strokeWidth={2} />
          <line x1={34} y1={42} x2={34} y2={46} stroke="#1a1a1a" strokeWidth={2} />
        </svg>
      );
    case 'diode':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <line x1={4} y1={cy} x2={14} y2={cy} stroke="#999" strokeWidth={1.5} />
          <polygon points={`${14},${cy - 6} ${14},${cy + 6} ${28},${cy}`} fill="none" stroke="#95a5a6" strokeWidth={1.5} />
          <line x1={28} y1={cy - 6} x2={28} y2={cy + 6} stroke="#95a5a6" strokeWidth={1.5} />
          <line x1={28} y1={cy} x2={44} y2={cy} stroke="#999" strokeWidth={1.5} />
        </svg>
      );
    case 'switch':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <line x1={4} y1={cy} x2={16} y2={cy} stroke="#999" strokeWidth={1.5} />
          <circle cx={16} cy={cy} r={2} fill="#bdc3c7" />
          <line x1={16} y1={cy} x2={32} y2={cy - 8} stroke="#bdc3c7" strokeWidth={1.5} />
          <circle cx={32} cy={cy} r={2} fill="#bdc3c7" />
          <line x1={32} y1={cy} x2={44} y2={cy} stroke="#999" strokeWidth={1.5} />
        </svg>
      );
    case 'zener':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <line x1={4} y1={cy} x2={14} y2={cy} stroke="#999" strokeWidth={1.5} />
          <polygon points={`${14},${cy - 6} ${14},${cy + 6} ${28},${cy}`} fill="none" stroke="#e67e22" strokeWidth={1.5} />
          <line x1={28} y1={cy - 6} x2={28} y2={cy + 6} stroke="#e67e22" strokeWidth={1.5} />
          <line x1={26} y1={cy - 8} x2={28} y2={cy - 6} stroke="#e67e22" strokeWidth={1} />
          <line x1={28} y1={cy} x2={44} y2={cy} stroke="#999" strokeWidth={1.5} />
        </svg>
      );
    case 'rgb_led':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <circle cx={cx} cy={cy - 4} r={10} fill="none" stroke="#999" strokeWidth={1} />
          <circle cx={cx - 3} cy={cy - 6} r={3} fill="#e74c3c" opacity={0.7} />
          <circle cx={cx + 3} cy={cy - 6} r={3} fill="#2ecc71" opacity={0.7} />
          <circle cx={cx} cy={cy - 2} r={3} fill="#3498db" opacity={0.7} />
          {[0, 1, 2, 3].map(i => <line key={i} x1={cx - 6 + i * 4} y1={cy + 6} x2={cx - 6 + i * 4} y2={cy + 14} stroke="#999" strokeWidth={1} />)}
        </svg>
      );
    case 'npn': case 'pnp':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <circle cx={cx} cy={cy} r={12} fill="none" stroke={color || '#8e44ad'} strokeWidth={1} />
          <line x1={8} y1={cy} x2={cx - 4} y2={cy} stroke="#999" strokeWidth={1.5} />
          <line x1={cx - 4} y1={cy - 8} x2={cx - 4} y2={cy + 8} stroke={color || '#8e44ad'} strokeWidth={2} />
          <line x1={cx - 4} y1={cy - 4} x2={cx + 8} y2={cy - 12} stroke={color || '#8e44ad'} strokeWidth={1.5} />
          <line x1={cx - 4} y1={cy + 4} x2={cx + 8} y2={cy + 12} stroke={color || '#8e44ad'} strokeWidth={1.5} />
          <text x={cx} y={cy + 22} textAnchor="middle" fill="#777" fontSize={7} fontFamily="monospace">{kind}</text>
        </svg>
      );
    case 'nmos': case 'pmos':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <circle cx={cx} cy={cy} r={12} fill="none" stroke={color || '#27ae60'} strokeWidth={1} />
          <line x1={8} y1={cy} x2={cx - 6} y2={cy} stroke="#999" strokeWidth={1.5} />
          <line x1={cx - 6} y1={cy - 8} x2={cx - 6} y2={cy + 8} stroke={color || '#27ae60'} strokeWidth={2} />
          <line x1={cx - 3} y1={cy - 8} x2={cx - 3} y2={cy + 8} stroke={color || '#27ae60'} strokeWidth={1} strokeDasharray="2 2" />
          <line x1={cx - 3} y1={cy - 5} x2={cx + 8} y2={cy - 12} stroke={color || '#27ae60'} strokeWidth={1.5} />
          <line x1={cx - 3} y1={cy + 5} x2={cx + 8} y2={cy + 12} stroke={color || '#27ae60'} strokeWidth={1.5} />
          <text x={cx} y={cy + 22} textAnchor="middle" fill="#777" fontSize={7} fontFamily="monospace">{kind}</text>
        </svg>
      );
    case 'opamp':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <polygon points={`8,${cy - 14} 8,${cy + 14} 38,${cy}`} fill="none" stroke={color || '#e67e22'} strokeWidth={1.5} />
          <text x={14} y={cy - 4} fill="#999" fontSize={8} fontFamily="monospace">+</text>
          <text x={14} y={cy + 8} fill="#999" fontSize={8} fontFamily="monospace">−</text>
          <line x1={38} y1={cy} x2={46} y2={cy} stroke="#999" strokeWidth={1.5} />
        </svg>
      );
    case 'inductor':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <line x1={4} y1={cy} x2={10} y2={cy} stroke="#999" strokeWidth={1.5} />
          <path d={`M 10 ${cy} Q 14 ${cy - 8} 18 ${cy} Q 22 ${cy - 8} 26 ${cy} Q 30 ${cy - 8} 34 ${cy} Q 38 ${cy - 8} 42 ${cy}`}
            fill="none" stroke={color || '#9b59b6'} strokeWidth={1.5} />
          <line x1={42} y1={cy} x2={46} y2={cy} stroke="#999" strokeWidth={1.5} />
        </svg>
      );
    case 'relay':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={8} y={8} width={32} height={32} rx={3} fill="#2c3e50" stroke={color || '#e67e22'} strokeWidth={1} />
          <path d={`M 14 ${cy} Q 18 ${cy - 6} 22 ${cy} Q 26 ${cy - 6} 30 ${cy} Q 34 ${cy - 6} 38 ${cy}`}
            fill="none" stroke={color || '#e67e22'} strokeWidth={1.5} />
          <text x={cx} y={14} textAnchor="middle" fill="#999" fontSize={7} fontFamily="monospace">RLY</text>
        </svg>
      );
    case 'servo':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={6} y={12} width={36} height={24} rx={3} fill="#2c3e50" stroke={color || '#f39c12'} strokeWidth={1} />
          <circle cx={30} cy={cy} r={5} fill="#555" stroke={color || '#f39c12'} strokeWidth={1} />
          <line x1={30} y1={cy} x2={34} y2={cy - 4} stroke="#bbb" strokeWidth={1.5} />
          {[0, 1, 2].map(i => <line key={i} x1={12 + i * 6} y1={36} x2={12 + i * 6} y2={42} stroke={['#e67e22', '#e74c3c', '#8B4513'][i]} strokeWidth={1.5} />)}
        </svg>
      );
    case 'dc_motor': case 'hobby_gearmotor':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <circle cx={cx} cy={cy} r={14} fill="#2c3e50" stroke={color || '#3498db'} strokeWidth={1.5} />
          <text x={cx} y={cy + 3} textAnchor="middle" fill="#ecf0f1" fontSize={10} fontFamily="monospace" fontWeight="bold">M</text>
          <line x1={cx - 14} y1={cy + 6} x2={cx - 20} y2={cy + 6} stroke="#999" strokeWidth={1.5} />
          <line x1={cx - 14} y1={cy - 6} x2={cx - 20} y2={cy - 6} stroke="#999" strokeWidth={1.5} />
        </svg>
      );
    case 'ldr':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <circle cx={cx} cy={cy} r={10} fill="#2c3e50" stroke={color || '#e67e22'} strokeWidth={1} />
          <path d={`M ${cx - 5} ${cy + 3} L ${cx - 3} ${cy - 3} L ${cx + 1} ${cy + 3} L ${cx + 3} ${cy - 3} L ${cx + 5} ${cy + 3}`}
            fill="none" stroke={color || '#e67e22'} strokeWidth={1.2} />
          <line x1={cx - 6} y1={cy - 10} x2={cx - 3} y2={cy - 7} stroke="#f39c12" strokeWidth={0.8} />
          <line x1={cx - 3} y1={cy - 12} x2={cx} y2={cy - 9} stroke="#f39c12" strokeWidth={0.8} />
          <line x1={4} y1={cy} x2={14} y2={cy} stroke="#999" strokeWidth={1.5} />
          <line x1={34} y1={cy} x2={44} y2={cy} stroke="#999" strokeWidth={1.5} />
        </svg>
      );
    case 'ntc':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={12} y={cy - 5} width={24} height={10} rx={2} fill="#2c3e50" stroke={color || '#16a085'} strokeWidth={1} />
          <text x={cx} y={cy + 3} textAnchor="middle" fill={color || '#16a085'} fontSize={7} fontFamily="monospace">NTC</text>
          <line x1={4} y1={cy} x2={12} y2={cy} stroke="#999" strokeWidth={1.5} />
          <line x1={36} y1={cy} x2={44} y2={cy} stroke="#999" strokeWidth={1.5} />
        </svg>
      );
    case '555':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={8} y={6} width={32} height={36} rx={2} fill="#2c3e50" stroke={color || '#e74c3c'} strokeWidth={1} />
          <text x={cx} y={cy + 2} textAnchor="middle" fill="#ecf0f1" fontSize={8} fontFamily="monospace" fontWeight="bold">555</text>
          <circle cx={12} cy={10} r={2} fill="#444" />
          {[0, 1, 2, 3].map(i => <rect key={`l${i}`} x={4} y={12 + i * 7} width={4} height={3} fill={color || '#e74c3c'} />)}
          {[0, 1, 2, 3].map(i => <rect key={`r${i}`} x={40} y={12 + i * 7} width={4} height={3} fill={color || '#e74c3c'} />)}
        </svg>
      );
    // Parts that reuse existing thumbnails
    case 'tip120': // darlington = transistor symbol
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <circle cx={cx} cy={cy} r={12} fill="none" stroke="#8e44ad" strokeWidth={1} />
          <line x1={8} y1={cy} x2={cx - 4} y2={cy} stroke="#999" strokeWidth={1.5} />
          <line x1={cx - 4} y1={cy - 8} x2={cx - 4} y2={cy + 8} stroke="#8e44ad" strokeWidth={2} />
          <line x1={cx - 4} y1={cy - 4} x2={cx + 8} y2={cy - 12} stroke="#8e44ad" strokeWidth={1.5} />
          <line x1={cx - 4} y1={cy + 4} x2={cx + 8} y2={cy + 12} stroke="#8e44ad" strokeWidth={1.5} />
          <text x={cx} y={cy + 22} textAnchor="middle" fill="#777" fontSize={6} fontFamily="monospace">TIP120</text>
        </svg>
      );
    case 'vsource':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={12} y={8} width={24} height={32} rx={4} fill="#2c3e50" stroke={color || '#f4d03f'} strokeWidth={1.5} />
          <text x={cx} y={cy - 2} textAnchor="middle" fill={color || '#f4d03f'} fontSize={14} fontFamily="monospace" fontWeight="bold">+</text>
          <text x={cx} y={cy + 10} textAnchor="middle" fill="#999" fontSize={7} fontFamily="monospace">−</text>
          <line x1={cx} y1={6} x2={cx} y2={2} stroke={color || '#f4d03f'} strokeWidth={1.5} />
          <line x1={cx} y1={40} x2={cx} y2={44} stroke="#999" strokeWidth={1.5} />
        </svg>
      );
    case 'photodiode':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <polygon points={`${14},${cy - 6} ${14},${cy + 6} ${28},${cy}`} fill="none" stroke="#f39c12" strokeWidth={1.5} />
          <line x1={28} y1={cy - 6} x2={28} y2={cy + 6} stroke="#f39c12" strokeWidth={1.5} />
          <line x1={4} y1={cy} x2={14} y2={cy} stroke="#999" strokeWidth={1.5} />
          <line x1={28} y1={cy} x2={44} y2={cy} stroke="#999" strokeWidth={1.5} />
          <line x1={10} y1={cy - 10} x2={16} y2={cy - 6} stroke="#f39c12" strokeWidth={0.8} />
          <line x1={14} y1={cy - 12} x2={20} y2={cy - 8} stroke="#f39c12" strokeWidth={0.8} />
        </svg>
      );
    case 'solar_cell':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={10} y={10} width={28} height={28} rx={2} fill="#1a2a4a" stroke="#f1c40f" strokeWidth={1} />
          <line x1={16} y1={14} x2={16} y2={34} stroke="#3498db" strokeWidth={0.5} />
          <line x1={24} y1={14} x2={24} y2={34} stroke="#3498db" strokeWidth={0.5} />
          <line x1={32} y1={14} x2={32} y2={34} stroke="#3498db" strokeWidth={0.5} />
          <line x1={14} y1={24} x2={34} y2={24} stroke="#3498db" strokeWidth={0.5} />
          <text x={cx} y={44} textAnchor="middle" fill="#f1c40f" fontSize={6} fontFamily="monospace">solar</text>
        </svg>
      );
    case 'light_bulb':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <circle cx={cx} cy={cy - 2} r={10} fill="none" stroke="#f39c12" strokeWidth={1.5} />
          <line x1={cx - 4} y1={cy - 6} x2={cx + 4} y2={cy + 2} stroke="#f39c12" strokeWidth={1} />
          <line x1={cx + 4} y1={cy - 6} x2={cx - 4} y2={cy + 2} stroke="#f39c12" strokeWidth={1} />
          <rect x={cx - 4} y={cy + 8} width={8} height={5} rx={1} fill="#bbb" stroke="#999" strokeWidth={0.5} />
        </svg>
      );
    case 'ultrasonic':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={6} y={12} width={36} height={24} rx={3} fill="#2c3e50" stroke="#3498db" strokeWidth={1} />
          <circle cx={16} cy={cy} r={6} fill="none" stroke="#3498db" strokeWidth={1.5} />
          <circle cx={32} cy={cy} r={6} fill="none" stroke="#3498db" strokeWidth={1.5} />
          {[0,1,2,3].map(i => <line key={i} x1={10+i*8} y1={36} x2={10+i*8} y2={42} stroke="#999" strokeWidth={1} />)}
        </svg>
      );
    case 'pir_sensor':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <circle cx={cx} cy={cy - 4} r={12} fill="#2c3e50" stroke="#27ae60" strokeWidth={1} />
          <circle cx={cx} cy={cy - 6} r={5} fill="none" stroke="#27ae60" strokeWidth={1.5} />
          {[0,1,2].map(i => <line key={i} x1={cx - 6+i*6} y1={cy + 8} x2={cx - 6+i*6} y2={cy + 14} stroke="#999" strokeWidth={1} />)}
        </svg>
      );
    case 'soil_moisture':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={18} y={4} width={12} height={30} rx={2} fill="#8B4513" stroke="#6d3a1f" strokeWidth={1} />
          <rect x={14} y={34} width={20} height={10} rx={2} fill="#2c3e50" stroke="#555" strokeWidth={1} />
          <line x1={20} y1={8} x2={20} y2={30} stroke="#a0522d" strokeWidth={0.5} />
          <line x1={28} y1={8} x2={28} y2={30} stroke="#a0522d" strokeWidth={0.5} />
        </svg>
      );
    case 'gas_sensor':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <circle cx={cx} cy={cy} r={12} fill="#2c3e50" stroke="#7f8c8d" strokeWidth={1.5} />
          <circle cx={cx} cy={cy} r={6} fill="none" stroke="#bbb" strokeWidth={1} />
          <text x={cx} y={cy + 3} textAnchor="middle" fill="#bbb" fontSize={6} fontFamily="monospace">MQ</text>
        </svg>
      );
    case 'tilt_sensor':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={16} y={10} width={16} height={24} rx={8} fill="none" stroke="#95a5a6" strokeWidth={1.5} />
          <circle cx={cx} cy={cy + 4} r={4} fill="#95a5a6" />
          <line x1={cx - 4} y1={34} x2={cx - 4} y2={42} stroke="#999" strokeWidth={1} />
          <line x1={cx + 4} y1={34} x2={cx + 4} y2={42} stroke="#999" strokeWidth={1} />
        </svg>
      );
    case 'slide_switch':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={10} y={cy - 6} width={28} height={12} rx={3} fill="#2c3e50" stroke="#bdc3c7" strokeWidth={1} />
          <rect x={18} y={cy - 4} width={8} height={8} rx={2} fill="#bdc3c7" />
          <line x1={4} y1={cy} x2={10} y2={cy} stroke="#999" strokeWidth={1.5} />
          <line x1={cx} y1={cy + 6} x2={cx} y2={cy + 14} stroke="#999" strokeWidth={1} />
          <line x1={38} y1={cy} x2={44} y2={cy} stroke="#999" strokeWidth={1.5} />
        </svg>
      );
    case 'dip_switch':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={8} y={12} width={32} height={24} rx={2} fill="#2c3e50" stroke="#bdc3c7" strokeWidth={1} />
          {[0,1,2,3].map(i => <rect key={i} x={12+i*7} y={16} width={4} height={8} rx={1} fill={i%2 === 0 ? '#bdc3c7' : '#555'} />)}
        </svg>
      );
    case 'neopixel':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={14} y={14} width={20} height={20} rx={2} fill="#111" stroke="#555" strokeWidth={1} />
          <circle cx={cx} cy={cy} r={6} fill="none" stroke="#2ecc71" strokeWidth={1} />
          <circle cx={cx - 2} cy={cy - 1} r={2} fill="#e74c3c" opacity={0.8} />
          <circle cx={cx + 2} cy={cy - 1} r={2} fill="#2ecc71" opacity={0.8} />
          <circle cx={cx} cy={cy + 2} r={2} fill="#3498db" opacity={0.8} />
        </svg>
      );
    case 'keypad':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={8} y={6} width={32} height={36} rx={3} fill="#2c3e50" stroke="#7f8c8d" strokeWidth={1} />
          {[0,1,2,3].map(r => [0,1,2].map(c => (
            <rect key={`${r}${c}`} x={14+c*8} y={10+r*8} width={5} height={5} rx={1} fill="#555" stroke="#777" strokeWidth={0.5} />
          )))}
        </svg>
      );
    case 'clock_display':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={4} y={14} width={40} height={20} rx={3} fill="#111" stroke="#e74c3c" strokeWidth={1} />
          <text x={cx} y={cy + 3} textAnchor="middle" fill="#e74c3c" fontSize={10} fontFamily="monospace">12:30</text>
        </svg>
      );
    case 'char_lcd_i2c':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={2} y={10} width={44} height={28} rx={3} fill="#1a4030" stroke="#2980b9" strokeWidth={1} />
          <rect x={6} y={14} width={36} height={20} rx={2} fill="#2a6040" />
          <text x={cx} y={cy + 2} textAnchor="middle" fill="#3c8" fontSize={7} fontFamily="monospace">I²C</text>
          <rect x={36} y={6} width={8} height={6} rx={1} fill="#2c3e50" stroke="#555" strokeWidth={0.5} />
        </svg>
      );
    case 'l293d':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={8} y={6} width={32} height={36} rx={2} fill="#2c3e50" stroke="#e74c3c" strokeWidth={1} />
          <text x={cx} y={cy - 2} textAnchor="middle" fill="#ecf0f1" fontSize={6} fontFamily="monospace">L293</text>
          <text x={cx} y={cy + 6} textAnchor="middle" fill="#ecf0f1" fontSize={6} fontFamily="monospace">D</text>
          <circle cx={12} cy={10} r={2} fill="#444" />
          {[0,1,2,3,4,5,6,7].map(i => <rect key={`l${i}`} x={4} y={8+i*4} width={4} height={2} fill="#e74c3c" />)}
          {[0,1,2,3,4,5,6,7].map(i => <rect key={`r${i}`} x={40} y={8+i*4} width={4} height={2} fill="#e74c3c" />)}
        </svg>
      );
    case 'relay_dpdt':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={6} y={8} width={36} height={32} rx={3} fill="#2c3e50" stroke="#e67e22" strokeWidth={1} />
          <path d={`M 14 ${cy} Q 18 ${cy-5} 22 ${cy} Q 26 ${cy-5} 30 ${cy} Q 34 ${cy-5} 38 ${cy}`} fill="none" stroke="#e67e22" strokeWidth={1.2} />
          <text x={cx} y={14} textAnchor="middle" fill="#999" fontSize={6} fontFamily="monospace">DPDT</text>
        </svg>
      );
    case 'pcf8574':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={8} y={6} width={32} height={36} rx={2} fill="#2c3e50" stroke="#8e44ad" strokeWidth={1} />
          <text x={cx} y={cy - 1} textAnchor="middle" fill="#ecf0f1" fontSize={5} fontFamily="monospace">PCF</text>
          <text x={cx} y={cy + 6} textAnchor="middle" fill="#ecf0f1" fontSize={5} fontFamily="monospace">8574</text>
          <circle cx={12} cy={10} r={2} fill="#444" />
          {[0,1,2,3,4,5,6,7].map(i => <rect key={`l${i}`} x={4} y={8+i*4} width={4} height={2} fill="#8e44ad" />)}
          {[0,1,2,3,4,5,6,7].map(i => <rect key={`r${i}`} x={40} y={8+i*4} width={4} height={2} fill="#8e44ad" />)}
        </svg>
      );
    case 'header':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          {[0,1,2,3,4,5,6,7].map(i => (
            <rect key={i} x={6+i*5} y={cy - 4} width={3} height={8} rx={0.5} fill="#f39c12" stroke="#b8860b" strokeWidth={0.5} />
          ))}
        </svg>
      );
    case 'usb_a':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={10} y={12} width={28} height={24} rx={2} fill="#bdc3c7" stroke="#999" strokeWidth={1} />
          <rect x={14} y={16} width={20} height={16} rx={1} fill="#fff" stroke="#ddd" strokeWidth={0.5} />
          <rect x={18} y={20} width={12} height={8} fill="#3498db" />
        </svg>
      );
    case 'ir_remote':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={10} y={8} width={28} height={32} rx={4} fill="#2c3e50" stroke="#c0392b" strokeWidth={1} />
          <circle cx={cx} cy={14} r={4} fill="#c0392b" opacity={0.6} />
          {[0,1,2,3,4,5].map(i => (
            <rect key={i} x={16+(i%3)*5} y={22+Math.floor(i/3)*6} width={4} height={4} rx={1} fill="#555" />
          ))}
        </svg>
      );
    case 'gearmotor': case 'motor_encoder': case 'vibration_motor':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <circle cx={cx} cy={cy} r={14} fill="#2c3e50" stroke={color || '#3498db'} strokeWidth={1.5} />
          <text x={cx} y={cy + 3} textAnchor="middle" fill="#ecf0f1" fontSize={10} fontFamily="monospace" fontWeight="bold">M</text>
          <line x1={cx - 14} y1={cy + 6} x2={cx - 20} y2={cy + 6} stroke="#999" strokeWidth={1.5} />
          <line x1={cx - 14} y1={cy - 6} x2={cx - 20} y2={cy - 6} stroke="#999" strokeWidth={1.5} />
        </svg>
      );
    case 'tmp36':
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <path d={`M ${cx - 5} ${cy + 8} L ${cx - 5} ${cy - 8} A 5 5 0 0 1 ${cx + 5} ${cy - 8} L ${cx + 5} ${cy + 8} Z`}
            fill="#1a1a2e" stroke="#16a085" strokeWidth={1.5} />
          <text x={cx} y={cy + 2} textAnchor="middle" fill="#16a085" fontSize={5} fontFamily="monospace">TMP</text>
          {[0, 1, 2].map(i => <line key={i} x1={cx - 4 + i * 4} y1={cy + 8} x2={cx - 4 + i * 4} y2={cy + 14} stroke="#999" strokeWidth={1} />)}
        </svg>
      );
    // 74HC logic chips — generic DIP package
    case '74hc00': case '74hc02': case '74hc04': case '74hc08':
    case '74hc10': case '74hc11': case '74hc14': case '74hc20':
    case '74hc21': case '74hc27': case '74hc32': case '74hc86':
    case '74hc74': case '74hc73': case '74hc93': case '74hc95':
    case '74hc132': case 'cd4017': case 'cd4511': {
      const label = kind.toUpperCase().replace('74HC', '74HC\u200B');
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={8} y={6} width={32} height={36} rx={2} fill="#2c3e50" stroke={color || '#9b59b6'} strokeWidth={1} />
          <circle cx={12} cy={10} r={2} fill="#444" />
          <text x={cx} y={cy - 1} textAnchor="middle" fill="#ecf0f1" fontSize={6} fontFamily="monospace">{kind.slice(0, 4).toUpperCase()}</text>
          <text x={cx} y={cy + 7} textAnchor="middle" fill="#ecf0f1" fontSize={6} fontFamily="monospace">{kind.slice(4)}</text>
          {[0, 1, 2, 3, 4, 5, 6].map(i => <rect key={`l${i}`} x={4} y={8 + i * 5} width={4} height={2.5} fill={color || '#9b59b6'} />)}
          {[0, 1, 2, 3, 4, 5, 6].map(i => <rect key={`r${i}`} x={40} y={8 + i * 5} width={4} height={2.5} fill={color || '#9b59b6'} />)}
        </svg>
      );
    }
    default:
      return (
        <svg width={w} height={h} viewBox={`0 0 ${S} ${S}`}>
          <rect x={8} y={8} width={32} height={32} rx={4} fill="none" stroke={color || '#555'} strokeWidth={1} strokeDasharray="4 2" />
          <text x={cx} y={cy + 3} textAnchor="middle" fill={color || '#777'} fontSize={8} fontFamily="monospace">{kind}</text>
        </svg>
      );
  }
}
